import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useOnboarding } from '../../contexts/OnboardingContext';
import { onboardingAPI, OnboardingDoc } from '../../api/onboarding';
import Card from '../../components/Card';
import Button from '../../components/Button';
import CatalogueUploader from '../../components/CatalogueUploader';

/**
 * Product Brochure post-launch view.
 *
 * Shows the founder's uploaded catalogue (PDF / DOCX / text) — the same
 * artifact attached during onboarding's knowledge_base step. Reuses the
 * existing CatalogueUploader component so the upload + preview UI is
 * consistent everywhere it appears.
 *
 * If no brochure has been uploaded yet, the uploader's empty state surfaces
 * the drop-zone + detected products, so the founder can attach one here too.
 */
export default function ProductBrochurePage() {
  const { company, loading: ctxLoading } = useOnboarding();
  const [doc, setDoc] = useState<OnboardingDoc | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!company?._id) return;
    setLoading(true);
    onboardingAPI
      .listDocs(company._id)
      .then(({ data }) => {
        const found = data.docs.find((d: OnboardingDoc) => d.kind === 'knowledge_base') || null;
        setDoc(found);
      })
      .finally(() => setLoading(false));
  }, [company?._id]);

  if (ctxLoading || loading) return <p className="mp-muted">Loading…</p>;

  if (!company) {
    return (
      <Card padding="lg" className="mp-text-center">
        <p className="mp-body-sm mp-muted">No company yet.</p>
        <Link to="/onboarding">
          <Button style={{ marginTop: 16 }}>Start onboarding</Button>
        </Link>
      </Card>
    );
  }

  // Detected products from website research — surfaced when nothing's uploaded.
  const detectedProducts: string[] = (() => {
    const fromAuto =
      (doc?.content as any)?.autoGenerated?.productsServices ||
      (doc?.content as any)?.productsServices ||
      [];
    if (Array.isArray(fromAuto) && fromAuto.length > 0) {
      return fromAuto.filter((s: any) => typeof s === 'string').slice(0, 6);
    }
    const fromWebsite = (company as any)?.research?.website?.products || [];
    return Array.isArray(fromWebsite)
      ? fromWebsite.filter((s: any) => typeof s === 'string' && !s.toLowerCase().includes('mock')).slice(0, 6)
      : [];
  })();

  return (
    <>
      <header className="mp-page-header">
        <h1 className="mp-page-header__title">Product brochure</h1>
        <p className="mp-page-header__subtitle">
          Your real product catalogue — what the AI references when it represents your company to leads.
        </p>
      </header>

      <Card padding="lg">
        <CatalogueUploader
          companyId={company._id}
          uploaded={(doc?.content as any)?.uploadedCatalogue || null}
          detectedProducts={detectedProducts}
          onUploaded={(updatedDoc) => setDoc(updatedDoc as OnboardingDoc)}
        />
      </Card>
    </>
  );
}
