import React, { useEffect, useMemo, useRef, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { RefreshCw, Upload, AlertTriangle } from 'lucide-react';
import { onboardingAPI, OnboardingDoc, OnboardingDocKind } from '../api/onboarding';
import PhaseProgress from '../components/PhaseProgress';
import Card from '../components/Card';
import Button from '../components/Button';
import DocRenderer from '../components/DocRenderer';
import DocEditor from '../components/DocEditor';
import DocThinking from '../components/DocThinking';
import WizardBackLink from '../components/WizardBackLink';
import CatalogueUploader from '../components/CatalogueUploader';
import { useOnboarding } from '../contexts/OnboardingContext';

const REVIEWABLE_ORDER: OnboardingDocKind[] = ['nurture_strategy', 'scoring_framework', 'brand_guidelines', 'knowledge_base'];

const DOC_TITLES: Record<OnboardingDocKind, string> = {
  nurture_strategy: 'Lead nurture playbook',
  scoring_framework: 'Lead scoring rules',
  brand_guidelines: 'Brand voice',
  target_profile: 'Target profile',
  knowledge_base: 'Product knowledge',
};

const DOC_SUBTITLES: Record<OnboardingDocKind, string> = {
  nurture_strategy:
    'The journey every lead follows — from first touch to your rep\'s calendar. Your AI handles the early stages, your rep takes the final meeting.',
  scoring_framework:
    'The rules that decide which leads are worth pursuing first. Every lead scores 0–100 across four factors; the score decides their stage.',
  brand_guidelines:
    'The tone, phrasing, and do/don\'t rules your AI follows when writing to leads — so every message sounds like you.',
  target_profile: 'Who you\'re selling to — locked in Phase A.',
  knowledge_base:
    'Upload your real product catalogue (brochure / deck / one-pager) so the AI uses your actual source material — not a generated guess.',
};

function getDetectedProducts(doc: OnboardingDoc, company: any): string[] {
  // Priority 1: AI-generated knowledge_base auto-content (productsServices)
  const fromAuto =
    doc?.content?.autoGenerated?.productsServices ||
    doc?.content?.productsServices ||
    [];
  if (Array.isArray(fromAuto) && fromAuto.length > 0) {
    return fromAuto.filter((s: any) => typeof s === 'string').slice(0, 6);
  }
  // Priority 2: research.website.products
  const fromWebsite = company?.research?.website?.products || [];
  if (Array.isArray(fromWebsite) && fromWebsite.length > 0) {
    return fromWebsite
      .filter((s: any) => typeof s === 'string' && !s.toLowerCase().includes('mock'))
      .slice(0, 6);
  }
  return [];
}

export default function OnboardingDocsPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { company } = useOnboarding();
  const [docs, setDocs] = useState<OnboardingDoc[]>([]);
  const [loading, setLoading] = useState(true);
  const [activeKind, setActiveKind] = useState<OnboardingDocKind>('nurture_strategy');
  const [draftContent, setDraftContent] = useState<any>(null);
  const [editing, setEditing] = useState(false);
  const [action, setAction] = useState<'idle' | 'approving' | 'skipping' | 'regenerating' | 'uploading' | 'regenerating-all'>('idle');
  const [error, setError] = useState('');
  // Sweep progress for "Regenerate all stale": null = not running.
  const [sweep, setSweep] = useState<{ done: number; total: number; current: string } | null>(null);
  const nurtureFileRef = useRef<HTMLInputElement>(null);

  const loadDocs = async () => {
    if (!id) return;
    setLoading(true);
    try {
      const { data } = await onboardingAPI.listDocs(id);
      setDocs(data.docs);
    } catch (e: any) {
      setError(e.response?.data?.error || 'Failed to load docs');
    } finally {
      setLoading(false);
    }
  };

  // Poll for doc updates while ANY doc is generating. Bumping `pollNonce`
  // re-arms the interval after a regenerate kicks off a new generation cycle.
  const [pollNonce, setPollNonce] = useState(0);
  useEffect(() => {
    loadDocs();
    const interval = setInterval(async () => {
      if (!id) return;
      const { data } = await onboardingAPI.listDocs(id);
      setDocs(data.docs);
      if (data.docs.every((d: OnboardingDoc) => d.status !== 'generating')) {
        clearInterval(interval);
      }
    }, 4000);
    return () => clearInterval(interval);
  }, [id, pollNonce]);

  const reviewableDocs = useMemo(() => docs.filter((d) => REVIEWABLE_ORDER.includes(d.kind)), [docs]);
  const activeDoc = docs.find((d) => d.kind === activeKind);
  const approvedCount = reviewableDocs.filter((d) => d.status === 'approved' || d.status === 'auto_approved').length;

  // Stale = doc was generated when AI was unavailable, so its rationale string
  // contains the "(AI fallback)" tag from fallbackFromTemplate(). Re-running
  // regenerate now will use Claude.
  const staleDocs = useMemo(
    () =>
      reviewableDocs.filter((d) => {
        const r = (d.content as any)?.rationale;
        return typeof r === 'string' && /AI fallback|vertical template/i.test(r);
      }),
    [reviewableDocs],
  );

  useEffect(() => {
    if (activeDoc) setDraftContent(activeDoc.content);
    setEditing(false);
  }, [activeDoc?._id]);

  const handleApprove = async () => {
    if (!id || !activeDoc) return;
    setAction('approving');
    setError('');
    try {
      const newContent = editing ? draftContent : undefined;
      await onboardingAPI.approveDoc(id, activeDoc.kind, { edited: editing, newContent });
      await loadDocs();
      const currIdx = REVIEWABLE_ORDER.indexOf(activeKind);
      const nextKind = REVIEWABLE_ORDER[currIdx + 1];
      if (nextKind) setActiveKind(nextKind);
      else navigate(`/onboarding/preview/${id}`);
    } catch (e: any) {
      setError(e.response?.data?.error || 'Approval failed');
    } finally {
      setAction('idle');
    }
  };

  const handleSkip = async () => {
    if (!id || !activeDoc) return;
    setAction('skipping');
    try {
      await onboardingAPI.skipDoc(id, activeDoc.kind);
      await loadDocs();
      const currIdx = REVIEWABLE_ORDER.indexOf(activeKind);
      const nextKind = REVIEWABLE_ORDER[currIdx + 1];
      if (nextKind) setActiveKind(nextKind);
      else navigate(`/onboarding/preview/${id}`);
    } finally {
      setAction('idle');
    }
  };

  const handleRegenerate = async () => {
    if (!id || !activeDoc) return;
    setAction('regenerating');
    setError('');
    // Optimistically mark the active doc as generating so DocThinking renders
    // the live ThinkingPanel immediately — the server has already started its
    // session by the time this paint completes.
    setDocs((prev) =>
      prev.map((d) => (d._id === activeDoc._id ? { ...d, status: 'generating' as any } : d)),
    );
    // Re-arm the listDocs polling effect so the UI auto-updates as the doc
    // progresses (the previous interval cleared once no docs were generating).
    setPollNonce((n) => n + 1);
    try {
      await onboardingAPI.regenerateDoc(id, activeDoc.kind);
      await loadDocs();
    } catch (e: any) {
      setError(e.response?.data?.error || e.message || 'Regenerate failed');
      // Roll back the optimistic update so the user can try again.
      await loadDocs();
    } finally {
      setAction('idle');
    }
  };

  // Sequentially regenerate every stale doc. Sequential (not parallel) because
  // each regen is a 30-60s Claude call — running 4 in parallel would spike
  // rate limits + make the dev experience worse than serial progress.
  const handleRegenerateAllStale = async () => {
    if (!id || staleDocs.length === 0) return;
    setAction('regenerating-all');
    setError('');
    const total = staleDocs.length;
    setSweep({ done: 0, total, current: staleDocs[0].title });

    // Optimistically mark all stale docs as generating so the UI shows progress.
    const staleIds = new Set(staleDocs.map((d) => d._id));
    setDocs((prev) =>
      prev.map((d) => (staleIds.has(d._id) ? { ...d, status: 'generating' as any } : d)),
    );
    setPollNonce((n) => n + 1);

    const failures: string[] = [];
    for (let i = 0; i < staleDocs.length; i++) {
      const d = staleDocs[i];
      setSweep({ done: i, total, current: d.title });
      try {
        await onboardingAPI.regenerateDoc(id, d.kind);
      } catch (e: any) {
        failures.push(`${d.title}: ${e.response?.data?.error || e.message || 'failed'}`);
      }
      await loadDocs();
    }
    setSweep(null);
    setAction('idle');
    if (failures.length > 0) {
      setError(`${failures.length} doc(s) failed to regenerate: ${failures.join(' · ')}`);
    }
  };

  const handleNurtureUpload = async (file: File) => {
    if (!id) return;
    setAction('uploading');
    setError('');
    try {
      const { data } = await onboardingAPI.uploadNurturePlaybook(id, file);
      setDocs((prev) => prev.map((d) => (d._id === data.doc._id ? data.doc : d)));
    } catch (e: any) {
      setError(e.response?.data?.error || 'Could not parse the playbook.');
    } finally {
      setAction('idle');
    }
  };

  if (loading) return <div className="mp-center"><p className="mp-muted">Loading your strategy docs…</p></div>;

  return (
    <div className="mp-app-shell">
      <div className="mp-wizard mp-wizard--wide" style={{ maxWidth: 1120 }}>
        <WizardBackLink to={id ? `/onboarding/leads/${id}` : '/onboarding'} label="Back to leads + feedback" />
        <PhaseProgress phase="phase_b" step={`b${REVIEWABLE_ORDER.indexOf(activeKind) + 1}`} />

        <div className="mp-text-center" style={{ marginBottom: 24 }}>
          <div className="mp-brand-header__overline">Phase B — Make my AI smart</div>
          <h2 className="mp-h2" style={{ margin: '6px 0 4px' }}>Review your AI's playbook</h2>
          <p className="mp-body-sm mp-muted">{approvedCount} of {REVIEWABLE_ORDER.length} docs approved</p>
        </div>

        {(staleDocs.length > 0 || sweep) && (
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 12,
              padding: '12px 16px',
              marginBottom: 16,
              background: 'rgba(252, 191, 73, 0.08)',
              border: '1px solid rgba(252, 191, 73, 0.4)',
              borderRadius: 'var(--radius-md)',
              color: 'var(--fg-0)',
            }}
          >
            <AlertTriangle size={18} style={{ color: '#c47a07', flexShrink: 0 }} />
            <div style={{ flex: 1, minWidth: 0 }}>
              {sweep ? (
                <>
                  <strong>Regenerating {sweep.done + 1} of {sweep.total}:</strong>{' '}
                  <span className="mp-muted">{sweep.current}</span>
                  <div
                    style={{
                      height: 4,
                      background: 'rgba(0,0,0,0.06)',
                      borderRadius: 2,
                      marginTop: 6,
                      overflow: 'hidden',
                    }}
                  >
                    <div
                      style={{
                        height: '100%',
                        width: `${(sweep.done / sweep.total) * 100}%`,
                        background: '#c47a07',
                        transition: 'width 250ms ease',
                      }}
                    />
                  </div>
                </>
              ) : (
                <>
                  <strong>{staleDocs.length} doc{staleDocs.length === 1 ? ' was' : 's were'} generated without AI</strong>{' '}
                  <span className="mp-muted">— Claude is now available; regenerate them to get personalised content.</span>
                </>
              )}
            </div>
            {!sweep && (
              <Button
                onClick={handleRegenerateAllStale}
                disabled={action !== 'idle'}
                size="sm"
              >
                <RefreshCw size={14} strokeWidth={2} /> Regenerate all stale
              </Button>
            )}
          </div>
        )}

        <div className="mp-doc-layout">
          {/* Sidebar */}
          <aside className="mp-stack" style={{ '--gap': 'var(--space-2)' } as any}>
            {REVIEWABLE_ORDER.map((kind) => {
              const doc = docs.find((d) => d.kind === kind);
              const active = kind === activeKind;
              return (
                <button
                  key={kind}
                  onClick={() => setActiveKind(kind)}
                  className={`mp-doc-tab ${active ? 'mp-doc-tab--active' : ''}`}
                >
                  <div className="mp-doc-tab__title">{DOC_TITLES[kind]}</div>
                  <div className="mp-doc-tab__status">
                    {doc ? (doc.status === 'approved' || doc.status === 'auto_approved' ? (
                      <span style={{ color: 'var(--mp-success)' }}>Approved</span>
                    ) : doc.status === 'ready_for_review' ? (
                      <span style={{ color: 'var(--mp-coral)' }}>Ready to review</span>
                    ) : doc.status === 'generating' ? (
                      <span>Generating…</span>
                    ) : doc.status === 'skipped' ? (
                      <span style={{ color: 'var(--mp-warning)' }}>Skipped</span>
                    ) : (
                      <span>Draft</span>
                    )) : <span>—</span>}
                  </div>
                </button>
              );
            })}

            <div className="mp-divider" style={{ marginTop: 12, marginBottom: 8 }} />
            <div className="mp-meta" style={{ padding: '0 4px' }}>Also generated (background):</div>
            <div className="mp-body-sm" style={{ padding: '0 4px', color: 'var(--fg-2)' }}>• Target profile</div>
          </aside>

          {/* Main */}
          <Card style={{ padding: 0, overflow: 'hidden' }}>
            {!activeDoc ? (
              <div className="mp-text-center mp-muted" style={{ padding: 48 }}>Select a doc to review.</div>
            ) : activeDoc.status === 'generating' ? (
              <DocThinking companyId={id!} docKind={activeDoc.kind} docTitle={activeDoc.title} />
            ) : (
              <>
                <header style={{ padding: 20, borderBottom: '1px solid var(--border-1)', display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 16 }}>
                  <div style={{ minWidth: 0, flex: 1 }}>
                    <h3 className="mp-h4" style={{ margin: 0 }}>{DOC_TITLES[activeDoc.kind]}</h3>
                    <p className="mp-body-sm mp-muted" style={{ margin: '4px 0 0', lineHeight: 'var(--lh-snug)' }}>
                      {DOC_SUBTITLES[activeDoc.kind]}
                    </p>
                    <div className="mp-meta" style={{ marginTop: 6 }}>
                      Generated in {activeDoc.generationIterations} iteration{activeDoc.generationIterations === 1 ? '' : 's'} · v{activeDoc.currentVersion}
                    </div>
                  </div>
                  <div style={{ display: 'flex', gap: 8, flexShrink: 0 }}>
                    {activeDoc.kind === 'nurture_strategy' && (
                      <>
                        <input
                          ref={nurtureFileRef}
                          type="file"
                          accept=".pdf,.docx,.txt,.md,.markdown"
                          style={{ display: 'none' }}
                          onChange={(e) => {
                            const f = e.target.files?.[0];
                            if (f) handleNurtureUpload(f);
                            e.target.value = '';
                          }}
                        />
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => nurtureFileRef.current?.click()}
                          disabled={action !== 'idle'}
                          title="Upload an existing playbook (PDF / DOCX) and we'll convert it to this format"
                        >
                          <Upload size={14} strokeWidth={2} />
                          {action === 'uploading' ? 'Parsing…' : 'Upload existing playbook'}
                        </Button>
                      </>
                    )}
                    <Button variant="ghost" size="sm" onClick={handleRegenerate} disabled={action !== 'idle'}>
                      <RefreshCw size={14} strokeWidth={2} /> Regenerate
                    </Button>
                  </div>
                </header>

                <div className="mp-doc-viewer" style={{ padding: 20 }}>
                  {/* Knowledge base gets the upload-first treatment */}
                  {activeDoc.kind === 'knowledge_base' && id && (
                    <CatalogueUploader
                      companyId={id}
                      uploaded={activeDoc.content?.uploadedCatalogue || null}
                      detectedProducts={getDetectedProducts(activeDoc, company)}
                      onUploaded={(updatedDoc) => {
                        setDocs((prev) => prev.map((d) => (d._id === updatedDoc._id ? updatedDoc : d)));
                      }}
                    />
                  )}

                  {editing ? (
                    <DocEditor doc={activeDoc} value={draftContent} onChange={setDraftContent} />
                  ) : activeDoc.kind !== 'knowledge_base' ? (
                    <DocRenderer doc={activeDoc} />
                  ) : null}
                </div>

                {error && <div style={{ padding: '0 20px' }}><p className="mp-help mp-help--error">{error}</p></div>}

                <footer style={{ padding: 20, borderTop: '1px solid var(--border-1)', display: 'flex', gap: 12, alignItems: 'center' }}>
                  {editing ? (
                    <>
                      <Button onClick={handleApprove} disabled={action !== 'idle'}>
                        {action === 'approving' ? 'Approving…' : 'Save + approve'}
                      </Button>
                      <Button variant="ghost" onClick={() => setEditing(false)}>Cancel</Button>
                    </>
                  ) : (
                    <>
                      <Button onClick={handleApprove} disabled={action !== 'idle' || activeDoc.status === 'approved'}>
                        {activeDoc.status === 'approved'
                          ? 'Already approved'
                          : action === 'approving'
                          ? 'Approving…'
                          : '✓ Approve as-is'}
                      </Button>
                      <Button variant="outline" onClick={() => setEditing(true)}>✏ Edit</Button>
                      <Button variant="ghost" size="sm" style={{ marginLeft: 'auto' }} onClick={handleSkip} disabled={action !== 'idle'}>
                        Skip for now →
                      </Button>
                    </>
                  )}
                </footer>
              </>
            )}
          </Card>
        </div>
      </div>
    </div>
  );
}
